<?php
/* LiangLeePanel
 * @website Link: http://community.elgg.org/pg/profile/arsalanlee/
 * @Package Liang Lee Framework
 * @subpackage LiangLeePanel
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2012.
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File start.php
 */
 
elgg_register_event_handler('init', 'system', 'LiangLeePanel');

/*
 * Register Plugin Settings
 *
 * @access admin
 */
function LiangLeePanel() {

elgg_extend_view('css/admin', 'LiangLeePanel/leepanel/css/css');

if (!elgg_is_active_plugin('LiangleeFramework')) {
 if (elgg_is_admin_logged_in()) {
 register_error(elgg_echo('lianglee:framewrok:miss'));
 } else {
 register_error(elgg_echo('lianglee:framewrok:miss:code'));	
     }
    }  
elgg_register_menu_item('Lianglee_admin_control_panel_cache', array(
	'name' => 'flush',
	'text' => elgg_echo('admin:cache:flush'),
	'href' => 'action/admin/site/flush_cache',
	'is_action' => true,
	'link_class' => 'elgg-button elgg-button-action',
));

elgg_register_menu_item('Lianglee_admin_control_panel_upgrade', array(
	'name' => 'upgrade',
	'text' => elgg_echo('upgrade'),
	'href' => 'upgrade.php',
	'link_class' => 'elgg-button elgg-button-action',
));
	
}
/*
 * Count Disk quota
 *
 * @param quota
 * @access admin
 */
function Lianglee_quota($bytes)
{
        $types = array( 'B', 'KB', 'MB', 'GB', 'TB' );
        for( $i = 0; $bytes >= 1024 && $i < ( count( $types ) -1 ); $bytes /= 1024, $i++ );
                return( round( $bytes, 2 ) . " " . $types[$i] );
}
/*
 * View Date
 * @string date ( string $format [, int $timestamp = time() ] )
 * @php 5.4  getdate ([ int $timestamp = time() ] )
 * @param $display
 * @access admin
 * @todo add to LiangLeeFramework 1.1.3
 */
function LiangLeePanelServer_date($display){
$date= date($display);
return $date;

}
/*
 * Server and execution environment information
 * The IP address of the server under which the current script is executing.
 * @string $_SERVER[variable]
 * @access admin
 * @todo add to LiangLeeFramework 1.1.3
 */
function LiangLeepanelServer_ip(){
$ip= $_SERVER['SERVER_ADDR'];
return $ip;
}