<?php
/* LiangLeePanel
 * @website Link: http://community.elgg.org/pg/profile/arsalanlee/
 * @Package Liang Lee Framework
 * @subpackage LiangLeePanel
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2012.
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File online.php
 */
 
if (elgg_is_admin_logged_in()) {
$usr = elgg_list_entities(array('type' => 'user','subtype'=> null,'full_view' => FALSE));
echo " <div class=\"elgg-body\">\n"; 
echo $usr; 
}
?>