<?php
/* LiangLeePanel
 * @website Link: http://community.elgg.org/pg/profile/arsalanlee/
 * @Package Liang Lee Framework
 * @subpackage LiangLeePanel
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2012.
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File quota.php
 */
if (elgg_is_admin_logged_in()) { 
$leediskused = disk_free_space(".");
$leedisktotal = disk_total_space(".");
$leeuseddisk = $leedisktotal - $leediskused;
$leebar = sprintf('%.2f',(  $leeuseddisk / $leedisktotal) * 100);
$leediskused = Lianglee_quota($leediskused);
$leeuseddisk = Lianglee_quota($leeuseddisk);
$leedisktotal = Lianglee_quota($leedisktotal);}
?>