<?php
/* LiangLeePanel
 * @website Link: http://community.elgg.org/pg/profile/arsalanlee/
 * @Package Liang Lee Framework
 * @subpackage LiangLeePanel
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2012.
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File php.php
 */
if (elgg_is_admin_logged_in()) { 
$apache= apache_get_modules();
foreach ($apache as $modules) {
echo "<ul class=\"LIANGLEECSS10061S\">\n"; 
echo "<li class=\"LIANGLEECSS10063FINE\"><span class=\"LIANGLEECSS10062\"></span><strong class=\"system_title\"><strong>".$modules."</strong></li>\n"; 
echo "</ul>\n";
}}
?>