<?php
/* LiangLeePanel
 * @website Link: http://community.elgg.org/pg/profile/arsalanlee/
 * @Package Liang Lee Framework
 * @subpackage LiangLeePanel
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2012.
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File perl.php
 */
 
/*
@todo add to LiangLeeFramework 1.1.3
*/
if (apache_get_modules(mod_perl)){
    $active = elgg_echo('lleepanel:info:perl:1');
    echo '<h3 class="LIANGLEECSSF465PERL">'.$active.'</h3>';

} else {
    $deactive =  elgg_echo('leepanel:info:perl:0'); 
    echo '<h3 class="LIANGLEECSSF464PERL">'.$deactive.'</h3>';

}

?>
