<?php
/* LiangLeePanel
 * FrameWork for Liang Lee Plugins
 * @package LiangLeeFramework 
 * @subpackage LiangLeePanel
 * @author Liang Lee
 * @copyright Copyright 2012, Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File Start.php
 */
 
$english = array(	
    'leepanel:stamp' => "Liang Lee",
	'leepanel:user:add' => "Add user",	
	'leepanel:plugins' => "Plugins",
	'leepanel:logochange' => "Change Logo",
    'leepanel:stse' => "Statistics",	
	'leepanel:dvelopers:settings' => "Developers Settings ",
	'leepanel:webemail' => "Website Email Setting",
	'leepanel:pwd:change' => "Change Password",
	'leepanel:unit:tests' => "Unit Tests",
	'leepanel:log:brow' => "Log browser",
	'leepanel:info:perl' => "Perl status",
	'leepanel:status:httpd' => "Apache Modules Status",
	'leepanel:dsk:quota' => "Disk Quota",	
 	'leepanel:rep:content' => "Reported Contents",	
	'leepanel:new:users' => "New users",
	'leepanel:cache:update' => "Cache and Upgrade", 
	'admin:administer_utilities:leepanel_apache' => "Apache Installed Modules Status",
	'llee:panel:logo' => "Please enter you custon logo url like http://www.youwebsite.com/logo.jpg",
	'llee:panel:settings' => "Liang Lee Panel Settings Page.",
	'admin:administer_utilities:leepanel_perl' => 'Mod Perl Status',
	'leepanel:footer:links:1' => "All copy right reserved",
	'leepanel:footer:links:2' => " Designed by",
    'leepanel:cpanel:dashboard' => "Control Panel",
	'leepanel:dsk:quota:used' => "% Disk Used",
	'leepanel:welcome' => "Welcome:",
	'leepanel:mc' => "Main Controls",
	'leepanel:advance:settings' => "Advanced Settings",
	'leepanel:basic:settings' => "Basic Settings",
	'leepanel:m:account' => "My Account",
	'leepanel:log:rotate' => "Log Rotate",
	'leepanel:sitestat' => "Site Stats",
	'leepanel:menuitems' => "Menu Items",
	'leepanel:on:users' => "Online Users",
	'leepanel:dashboard:widgets' => "Dashboard widgets",
	'leepanel:ibox' => "Inbox",
	'leepanel:profilefield' => "Profile Field",
	'leepanel:extend:bar' => "More",
	'leepanel:gurbcollect' => "Garbage Collector",
	'leepanel:dashboard:label' => "Dashboard",
	'leepanel:server:adr' => "Server address :",
	'lleepanel:server:time' => "Server time :",
	'lleepanel:info:perl:1' => "Good news mod perl is active",
	'leepanel:info:perl:0' => "Bad news mod Perl is  deactive",



 );
					
add_translation("en", $english);
?>