<?php
/* LiangLeePanel
 * @website Link: http://community.elgg.org/pg/profile/arsalanlee/
 * @Package Liang Lee Framework
 * @subpackage LiangLeePanel
 * @author Liang Lee
 * @copyright All right reserved Liang Lee 2012.
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File php.php
 */
if (elgg_is_admin_logged_in()) {
echo elgg_view_menu('Lianglee_admin_control_panel_upgrade', array(
	'class' => 'elgg-menu-hz',
	'item_class' => 'mrm',
));
}
?>